### ISSUE TITLE
Nothing comes up.

### ISSUE THREAD

**Issue by GeneralAwareness** [victorchall/EveryDream#22]
![image](https://user-images.githubusercontent.com/124339252/227139832-66335b1b-3007-4286-b35e-43460e777457.png)

I installed everything in the requirements.txt file then I ran python scripts\image_caption_gui.py but all I get is what is in this image.
![image](https://user-images.githubusercontent.com/124339252/227140383-aaa44a0c-374b-4790-aa5f-4fa760375e2c.png)
What am I doing wrong?

**Comment by victorchall** [comment]
https://github.com/victorchall/EveryDream/blob/main/doc/CAPTION_GUI.md 

Instructions are there.  It is super bare bones.  Try Ctrl-O and pick a folder

**Comment by GeneralAwareness** [comment]
Thank you.
