### ISSUE TITLE
Is it possible to resize smallest dimension to the target size, and then randomly crop the final amount during training?

### ISSUE THREAD

**Issue by ProGamerGov** [victorchall/EveryDream#8]
Its not very clear from documentation whether or not this is possible yet in this project's code, unless I'm missing something major.

I would like to resize my training images so that their smallest dimension is for example 512px, and then the larger dimension is whatever larger size. Then during training, the a random 512x512 section is cropped from the 512 by whatever size image. The caption information for the full image would remain attached to the crop made from it.

**Comment by victorchall** [comment]
It's better not to try to trick the resizing and cropping algorithm...  Keep your original images in at least like 1kx1k resolution and let the code deal with it from there.

Only crop to focus on the context you want trained.  

The cropping is very minor, and I only trim like 2-3% off the sides randomly every repeat, and square or close to square images I do a focus and random crop of 98% or so of the area.

Please don't attempt outsmart it, you'll end up causing problems.  Also high res support is coming. Keep your originals!!!

People already reporting some really spectacular results....
